version = 1

exclude_patterns = ["lib/phpmailer/*"]

[[analyzers]]
name = "php"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = ["jquery"]

[[transformers]]
name = "php-cs-fixer"